# Generated by Django 5.2.5 on 2025-08-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway',
        ),
    ]
