# Generated by Django 5.2.5 on 2025-08-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.pipeline'),
        ),
    ]
