# Generated by Django 5.2.5 on 2025-08-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads_description_leads_pipeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='pipeline',
            new_name='status',
        ),
    ]
