# Generated by Django 5.2.5 on 2025-08-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_pipeline_leads_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
    ]
