# Generated by Django 5.2.5 on 2025-08-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leads_options'),
        ('pipelines', '0006_remove_pipeline_order_remove_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.pipelinestatus'),
        ),
        
    ]
