# Generated by Django 5.2.5 on 2025-08-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leads_pipeline_alter_leads_status'),
        ('pipelines', '0008_alter_pipelinestatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='pipelines.pipeline'),
        ),
    ]
