# Generated by Django 5.2.5 on 2025-08-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpstore_created_at_otpstore_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('sale', 'sales'), ('ref', 'referrer')], default='ref', max_length=10),
        ),
    ]
