# Generated by Django 5.2.5 on 2025-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpstore_created_at_otpstore_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
