# Generated by Django 5.2.5 on 2025-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
