# Generated by Django 5.2.5 on 2025-08-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestages',
            name='pipeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline'),
            preserve_default=False,
        ),
    ]
