# Generated by Django 5.2.5 on 2025-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_pipelinestages_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='is_active',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stage',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('customer', 'Customer'), ('closed', 'Closed')], default='new', max_length=100),
        ),
        migrations.DeleteModel(
            name='PipelineStages',
        ),
    ]
