# Generated by Django 5.2.5 on 2025-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_remove_pipeline_is_active_pipeline_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('customer', 'Customer'), ('closed', 'Closed')], default='new', max_length=100),
        ),
    ]
