# Generated by Django 5.2.5 on 2025-08-19 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_alter_pipeline_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='stage',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('customer', 'Customer'), ('closed', 'Closed')], default='closed', max_length=100, null=True)),
                ('pipeline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
