# Generated by Django 5.2.5 on 2025-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_remove_pipeline_order_remove_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestatus',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('customer', 'Customer'), ('closed', 'Closed')], default='new', max_length=100, null=True),
        ),
    ]
