# Generated by Django 5.2.5 on 2025-08-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_pipelinestatus_stage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipelinestatus',
            unique_together={('pipeline_name', 'stage')},
        ),
    ]
