# Generated by Django 5.2.5 on 2025-08-21 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_alter_pipelinestatus_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='own_pipeline', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),
    ]
