# Generated by Django 5.2.5 on 2025-08-22 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_pipeline_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('name', 'user', 'owner')},
        ),
    ]
